#!/bin/bash
if [ -f /usr/lib/python3.5/site-packages/powerline/bindings/tmux/powerline.conf ]; then
	tmux source /usr/lib/python3.5/site-packages/powerline/bindings/tmux/powerline.conf
elif [ -f /usr/share/powerline/bindings/tmux/powerline.conf ]; then
	tmux source /usr/share/powerline/bindings/tmux/powerline.conf
fi
